### ISSUE TITLE
tsOfficial setting is ignored

### ISSUE THREAD

**Issue by lumaxis** [vscode-icons/vscode-icons#1015]
- [x] I'm sure this issue is not a *duplicate*
- [ ] I want to create an icon request(if not, remove these lines below)

No matter if I set `"vsicons.presets.tsOfficial": false` to `true` or `false`, or even remove it entirely, I always see the official TS icon displayed in my files list:

<img width="153" alt="screenshot 2017-06-09 15 21 31" src="https://user-images.githubusercontent.com/406937/26977222-54c10a1e-4d27-11e7-8421-c4863294e95c.png">

**Comment by robertohuertasm** [comment]
Have you checked out your workspace settings?

**Comment by lumaxis** [comment]
Yes, no `vsicons` settings in there either 😕

**Comment by robertohuertasm** [comment]
This is very strange... Try reinstalling the extension.

**Comment by lumaxis** [comment]
Wow, weird. That appears to have worked. I had tried disabling and re-enabling before but no complete reinstall. Thanks!

**Comment by JimiC** [comment]
You missed using `F1>Icons: Apply Icons Customization` after you set the preset.

**Comment by robertohuertasm** [comment]
I somehow thought he was using the toggle preset but clearly that might have been the case.

**Comment by lumaxis** [comment]
@JimiC @robertohuertasm Yes, that's absolutely true! I totally missed that that is a necessary step!

Imo, it's very hard to discover that there is an additional step necessary to actually apply a setting. The maximum that I would have expected was a VS Code restart but even that doesn't actually apply the preset. Would it technically be possible to change this flow or for example prompt the user to trigger the "apply" after changing the settings?

**Comment by jens1o** [comment]
We could consider doing this on `deactivate`, but that would slow down the process quiting, and I don't know what would happen when all extensions do that sync... The shutdown experience would be awful.

**Comment by JimiC** [comment]
I believe it's possible to detect when the presets have been manually changed and display the prompt to restart `vscode` in order for the icon manifest to be re-build. It will require some further investigation.

**Comment by robertohuertasm** [comment]
It's possible, indeed, as seen [here](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_workspace) but we should be very careful with this as we don't want to show a prompt for any modification happening in the configuration files. The idea of leaving this process completely unobstrusive was to not annoy the user with every time she changes the configuration.

From my point of view, @lumaxis not getting the thing to work was because a) he didn't look deep into the docs or b) the docs are not clear enough. No offense @lumaxis but I lean to a) as the docs are very clear in this regard and the note is just behind the preset explanation:

![image](https://user-images.githubusercontent.com/696981/26995656-2f665264-4d6e-11e7-94d2-11f49e0d9e23.png)

That being said, if I would have to develop this I would make this like the `show welcome message prompt` and allow the user to avoid showing this more than once if she wants.

**Comment by lumaxis** [comment]
@robertohuertasm None taken and absolutely fair point!

My biggest issue with this is discoverability and the way this differs from my (and I'm naively presuming other users') expectation of how settings in VS Code work. I have not ever seen another built-in VS Code setting or extension setting that required me to execute a manual task without me explicitly prompting about it. And I really customize a lot of things 🙂 

The only things that I have experienced so far are were extensions that either required me to reload/restart or click a button in the toast that showed after I changed a setting. The way vscode-icons handles this right now is in my opinion not optimally designed as it goes against everything I'm used to since the time I started using VS Code.
I strongly disagree with you on this:
>The idea of leaving this process completely unobstrusive was to not annoy the user with every time she changes the configuration.

While I agree that it's a good goal to be unobtrusive, I don't think it's unreasonable to show a toast when a user manually changes a setting. Realistically, how often does a user change a preset? And when they do, are there many cases where they would **not** want to apply them?

My point boils down to this: It's all good that this is documented and the documentation well written and clear but in my view, a well-designed system should be usable _without_ **having** to read the documentation.

But then again, maybe this isn't a problem for other users at all? The lack of other Issues about the same problem surprised me, so maybe I'm totally wrong here 🙂

**Comment by robertohuertasm** [comment]
@lumaxis you definitely have a point. My main concern is being to intrusive with prompts because I've seen how some of my colleagues get tired of prompts and then they don't even read them.

As I said, I'll be fine with this if we can find a way to:

1. React only to changes affecting `vscode-icons` settings
2. Allow the user to turn on/off this behavior.

Let's see what @JimiC & @jens1o have to say and in case they're in we'll add a new issue with this task.

**Comment by JimiC** [comment]
The think is that `vscode` itself using the detection technic upon saving the settings file to enable/disable its features and settings. And this is what the user expects as a UX from the extensions as well. So @lumaxis has a strong point. On the other hand, we had our shares of complaints about being intrusive and we are now very cautious with it. There is also an [issue](https://github.com/Microsoft/vscode/issues/27993) on `vscode` about extensions messages being too annoying.

>1. React only to changes affecting vscode-icons settings

I'm confident that this is achievable.

>2. Allow the user to turn on/off this behavior.

This is the tricky part.

**Comment by JimiC** [comment]
@robertohuertasm I have already coded section 1. Should I proceed with section 2 or is it something you are not interested in implementing?

**Comment by robertohuertasm** [comment]
@JimiC you can proceed. No problem.
