### ISSUE TITLE
Improves Github TEMPLATE

### ISSUE THREAD

**Issue by torn4dom4n** [vscode-icons/vscode-icons#1336]
The Github template is not good enough so I want to improve it. Moved from https://github.com/vscode-icons/vscode-icons/pull/1335.

**Comment by JimiC** [comment]
IMO, as I'm the last that edited the templates, I think they don't need any changing. 
My change just fixed the markdown formatting and added some more placeholders to give a hint to the user what needs to be filled.
Personally, I don't care about `Atom` or `VSCode` or `GitHub` or any other platform templates.
Templates are to be opinionated and not standardized.
That said, with respect to @robertohuertasm, I leave it up to him to decide on this.

**Comment by torn4dom4n** [comment]
When I open an issue, I feel not comfortable because I need to delete the hints. I think can move them into the comments of markdown. These comments help description to the user.

**Comment by JimiC** [comment]
The placeholders are there to provide also the preferred markdown formatting.
In your proposal, as a user, you don't gain anything. You'll still have to delete the comments. We don't any leftover comments on the issues or PRs.

**Comment by torn4dom4n** [comment]
Oh, the comments don't appear on the issues or PRs, they only appear if you edit the issues or PRs. I think it is enough to tell the user what to do.

**Comment by JimiC** [comment]
Exactly what I'm saying. Personally, I don't like any leftover comments, even if they aren't visible. I believe the rest of the team feels the same. But that's just me.

**Comment by torn4dom4n** [comment]
For me, don't need to delete the comments because it is "the comments".

**Comment by jens1o** [comment]
Well, at least you'll need to deal a little bit of time with it, which increases the quality of these issues by an impressive amount. ;)

Otherwise, I agree with @JimiC

**Comment by JimiC** [comment]
@jens1o From my personal experience, dealing with maintaining popular repos, I came to the conclusion that a user likes to spend, as less time as possible, writing an issue. I believe that's also @torn4dom4n motive for the proposal. The ideal would be to just write the title and the maintainers would instantly understand what the issue is all about. But that hasn't been invented yet, unfortunately (I speak for myself as well). :tongue:
My belief is that the templates are just on top of the golden line between what the user wants to do and what info we require from the user.

**Comment by jens1o** [comment]
What would we be without you?

😍 ;)

**Comment by JimiC** [comment]
![](https://media.giphy.com/media/J6CabqLkgCiQg/giphy.gif)

**Comment by robertohuertasm** [comment]
Personally, I don't dislike the idea of leftover comments. Having the option of not having to delete all the instructions in order to raise an issue or create a new PR I think it's great. What we now have enforces the user to delete some of the lines. By using comments we would let the user decide: if he doesn't like the idea of leaving these comments then he will delete the lines (exactly as he does right now). Otherwise, if the user is lazy as I am, he will have the option to not deleting them and not having to worry about these comments being visible.

My point is that by using comments we let the users chose what they want to do with the leftovers. As the comments are not visible once the issue/PR is created, this would make both the lazy and the ocd devs happy. :wink: 

That being said, I share @JimiC's point of view about using copies of other project templates. We have our own needs and preferences so I wouldn't drastically change our current templates.

**Comment by JimiC** [comment]
I'm willing to give this a chance, but I'm going to propose a different approach than the one proposed in #1335.

**Comment by JimiC** [comment]
My proposal has been submitted to #1381. As you can see the template now has all the info needed inside the comments, which makes it look cluttered, at least the `ISSUE_TEMPLATE`. 
Another approach would be to move all those info to the wiki and add a link to that in the template.
Thoughts?

**Comment by robertohuertasm** [comment]
@JimiC, I agree with linking to the wiki and just keep the scaffolding.
