### ISSUE TITLE
Apiblueprint Icon not showing

### ISSUE THREAD

**Issue by pedrosalpr** [vscode-icons/vscode-icons#1364]
As I said in issue [#167](https://github.com/vscode-icons/vscode-icons/issues/167), the apiblueprint icon is not being shown.

OS: MacOS High Sierra
Version of Vscode: 1.18.1
Version of Vscode-icons: 7.18.1

![captura de tela 2017-11-17 as 11 18 13](https://user-images.githubusercontent.com/5918761/32949219-2eef6b56-cb89-11e7-9759-d3d45409d2fe.png)

**Comment by JimiC** [comment]
Please read the [wiki](https://github.com/vscode-icons/vscode-icons/wiki/ListOfFiles).

**Comment by jens1o** [comment]
@JimiC He already stated that
>The apib extension does not handle the apiblueprint icon.

**Comment by JimiC** [comment]
What @pedrosalpr doesn't say is which extension is that, if any. Any link?

**Comment by jens1o** [comment]
No need to close them so fast, we can simply add the `more information needed` label.

**Comment by JimiC** [comment]
@jens1o I know it works with https://marketplace.visualstudio.com/items?itemName=vncz.vscode-apielements. There is nothing to fix.

**Comment by pedrosalpr** [comment]
@JimiC  Okay I installed the extension and it worked, but it should not automatically assign the icon, without needing another extension (vncz.vscode-apielements), I do not even make use of this extension that you passed. And I installing the extension, is leaving the purpose of the vscode-icons extension.

**Comment by JimiC** [comment]
@pedrosalpr On the contrary. By installing the syntax highlighting extension you gain more than just the icon showing.
If you are using another `apib` extension and the icon isn't showing, then we'd like to know about that extension.

**Comment by pedrosalpr** [comment]
I know that gain more than a simple icon. But you could add the `apib` extension to the apiblueprint icon. And it would solve this problem. And he would not need another extension. The extent of vscode-icons, in my opinion, it should be independent of any other extension.

**Comment by JimiC** [comment]
@pedrosalpr I'm sorry I don't understand which is the `apib` extension you are mentioning.

**Comment by pedrosalpr** [comment]
Adds support that when I have a file with the `apib` extension, it adds the `apiblueprint` icon.

**Comment by JimiC** [comment]
We already do that via the above-mentioned 3rd party extension. This is a decision we consciously made.

**Comment by pedrosalpr** [comment]
Ok. Thank you.

**Comment by robertohuertasm** [comment]
@pedrosalpr, just to give you more information. Normally, we only associate file extensions to icons when there's not any `language extension` available. Why is that? Certainly, you end up needing another extension just to see the icon but the cool thing is that we don't have to worry about the real file extension at all. If tomorrow, let's say, instead of `.apib`, another extension called `.apib2` appears, the language extension will make it possible to do this association automatically without us having to take care of everything. It also allow us to change the icon depending on the language association you decide to have.

Anyway, if you're not happy with this and you don't want to install another extension you can always use our [custom icon associations](https://github.com/vscode-icons/vscode-icons/wiki/FineTuning). I encourage you to take a look at it. I'm sure you will like it. 😉

**Comment by JimiC** [comment]
@robertohuertasm I couldn't have said it better. It's just not my day today.

**Comment by JimiC** [comment]
@pedrosalpr Following the discussion on https://github.com/vscode-icons/vscode-icons/issues/1363, you can achieve the icon to show without installing a syntax highlighting extension by adding:
```
"vsicons.associations.files": [
        { "icon": "apib", "extensions": ["apib"], "format": "svg" }
      ]
```
in your `User Settings`.
