### ISSUE TITLE
Elixir's .eex icon, is not displaying

### ISSUE THREAD

**Issue by GeorgeKaraszi** [vscode-icons/vscode-icons#1414]
Noticing that in all my projects the icon's for HTML (Eex) `.eex` files are not loading the standard Elixir icon.

![proof](https://user-images.githubusercontent.com/9029051/34641623-dfd7c356-f2d4-11e7-9091-9576e8931a96.png)

**Comment by JimiC** [comment]
Hm, right. We need to support also `Eex` `language id` (https://github.com/fr1zle/vscode-elixir/blob/master/package.json#L49)

**Comment by JimiC** [comment]
And by looking how we support other templates, any suggestions on an icon?

**Comment by JimiC** [comment]
Just got an idea inspired by [this](https://pbs.twimg.com/profile_images/893174750708510721/YzVVy8fm_400x400.jpg). Will work on it tomorrow.

**Comment by JimiC** [comment]
Update
----
Turns out that we already support `Eex` and `HTML (Eex)` after all. But with `HTML (Eex)` we are hitting the known `vscode` snag, it not liking whitespaces in the `language id`.
In order to fix this @fr1zle needs to fix first the language ids.
According to the [guidelines](https://code.visualstudio.com/docs/languages/identifiers#_new-identifier-guidelines):
- `Eex` needs to be switched to `eex`
- `HTML (Eex)` needs to be switched to `html-eex` or `html_eex` (though `kebabcase` is the standard for defining multi-word ids)

I do realize that this is a breaking change for the `elixir` extension but it's a necessary one in order to support icons for `.html.eex` files.

Never the less, a have created a new icon for Elixir templates which will be included when the `html.eex` 
 id can be properly supported.

**Icon Preview:** ![file_type_eex](https://user-images.githubusercontent.com/1716442/34649486-006db6a4-f3b9-11e7-93bc-d7941080dc44.png)

**Editor Preview:** ![screenshot - 07_01_2018 14_44_12](https://user-images.githubusercontent.com/1716442/34649507-53d6f7a6-f3b9-11e7-9c68-72fe3f0d948d.png) ![screenshot - 07_01_2018 14_45_56](https://user-images.githubusercontent.com/1716442/34649517-8a15a59c-f3b9-11e7-9d32-33fd01354e1e.png)

**Comment by fr1zle** [comment]
This has been on my bucket list for a while. Will open an issue in my repo and see what the implications are of that change.

**Comment by JimiC** [comment]
@fr1zle While we are at it I strongly suggest using `Embedded Elixir` instead of `Eex` in the `aliases` section. That way `Embedded Elixir (eex)` will be shown in the language mode selection menu.

**Comment by fr1zle** [comment]
@JimiC does this look good to you? https://github.com/fr1zle/vscode-elixir/pull/114

**Comment by ahmetcetin** [comment]
is there anything to be done to enable this? Still .html.ees files are not shown properly it looks.

<img width="431" alt="Untitled" src="https://user-images.githubusercontent.com/5046786/57440863-10b53180-7249-11e9-8c34-c8a0451034be.png">

**Comment by JimiC** [comment]
@ahmetcetin Install an `Elixir` syntax highlighting extension from the marketplace that supports `Html (eex)`

**Comment by JimiC** [comment]
@ahmetcetin Your issue is related to https://github.com/fr1zle/vscode-elixir/issues/113.

**Comment by ahmetcetin** [comment]
gr8, thx, it looks that pull request stuck long time there, I just manually made the changes in my installation, and it worked.
