### ISSUE TITLE
Default File Icon Association Only Works for "file"

### ISSUE THREAD

**Issue by McPrescott** [vscode-icons/vscode-icons#1427]
- [x] I'm sure this issue is not a _duplicate_.

The `vsicons.associations.fileDefault.file` setting only works with the `"icon": "file"`. I've tried several different icons, with a variety of different formats ("svg", "FileFormat.svg", etc.) and everything other than `file` does not work. I've attached two screenshots demonstrating the issue. 

![vs-code-icons](https://user-images.githubusercontent.com/20735042/35360681-cf2fd796-011b-11e8-95e6-1be3771aa097.png)

![vs-code-icons 2](https://user-images.githubusercontent.com/20735042/35360683-cf51ceb4-011b-11e8-9b80-95dfb8ba9157.png)

I apologize if this is a duplicate question or is covered in the wiki. I've been searching through the repository and have not yet found a solution. I'm not sure if the issue is a bug, or is just a syntax error.

**Any help is greatly appreciated.**
**Thank you in advance.** 👍

**Comment by JimiC** [comment]
Indeed `vsicons.associations.fileDefault.file` is a customization setting for customizing the `default` file.
If you want to customize any other `file` icon you need to use the `vsicons.associations.files` customization setting.
This is covered in https://github.com/vscode-icons/vscode-icons/wiki/FineTuning#fine-tuning

**Comment by McPrescott** [comment]
Oh I apologize. I was under the misunderstanding that `vsicons.associations.fileDefault.file` allowed you to change the default file to an arbitrary icon within the repository. 

What I wanted was for extensionless files to use the `shell` icon. I wasn't exactly sure how to do so and thought that if were to change the default `file` icon I would achieve a similar result; 99% of the files in the projects I work on are covered in this extension (good work on that btw 👍 very appreciative for these icons) and it is safe to assume that files that are not recognized are shell scripts.

**Comment by JimiC** [comment]
Yeap, you need to use `vsicons.associations.fileDefault.file` in that case, but it needs a little more fine-tuning.

**Comment by JimiC** [comment]
@McPrescott The `default file` customization doesn't support the `overrides` and `extends` functionality like the other icons do. Maybe this is a good opportunity to add them to it.
In order to achieve what you want, you need to set up a `vsicons-custom-icons` folder and put the `shell` icon in there, as described in [Custom Icons](https://github.com/vscode-icons/vscode-icons/wiki/Custom). Unfortunately, we only just a few days ago added the ability to set the `vsicons-custom-icons` folder path to a relative path to the project, using the `vsicons.customIconFolderPath` setting. So it's not available yet.

I'm gonna leave this open until we release the new version. Hopefully, we may have added the above-mentioned functionality, for the `default file` too.

**Comment by McPrescott** [comment]
An absolute path would be fine for the time being. Thank you @JimiC you have been very helpful! 😄

**Comment by JimiC** [comment]
I looked into adding `extends` functionality to the `default` files and folders but unfortunately, this is more complex than it looks and I'm afraid that it may destabilize the extension.
Still, though the way to achieve what the OP wants is to create the `vsicons-custom-icons` folder as described in [Custom Icons](https://github.com/vscode-icons/vscode-icons/wiki/Custom) and copy inside it the preferred icon and remain it accordingly (i.e.`default_<value_of_icon_property>.<icon_file_extension>`).
