### ISSUE TITLE
[Icon Request] Support for PostgreSQL

### ISSUE THREAD

**Issue by brennongs** [vscode-icons/vscode-icons#1481]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `language id`
  - Icon Name: `PostgreSQL`
  - Sample original Icon: ![logo](https://upload.wikimedia.org/wikipedia/commons/2/29/Postgresql_elephant.svg)
  - Language ids: `pgsql`

- Language Extensions: https://marketplace.visualstudio.com/items?itemName=doublefint.pgsql

**Comment by JimiC** [comment]
@brennongs Thanks for your request. At this point, I like to remind you all to first read <https://github.com/vscode-icons/vscode-icons/wiki/Issue> before submitting an issue.
That said, I took the liberty to correct your request as it contained many errors.

Now, to the point, thanks for reminding me to do that. Been wanting to add that since I added `sqlite` but totally forgot about it.
