### ISSUE TITLE
The vsicons.customIconFolderPath setting only works if the path is on drive C:

### ISSUE THREAD

**Issue by johnhamm** [vscode-icons/vscode-icons#1904]
- [x] I'm sure this issue is not a _duplicate_.

The `vsicons.customIconFolderPath` setting only works if the path is on drive C:.  If I keep all the settings the same but change to my shared network drive P:, it doesn't work.  If I change it to my external USB drive plugged directly in to my computer on drive D:, it doesn't work:

Drive E
![2019-03-07 23_36_12-c__users_john_appdata_roaming_code_user_settings json - clientapp - visual studi](https://user-images.githubusercontent.com/3343496/54007849-da1c4700-4131-11e9-97e3-b7546167707a.png)
 or Drive P:

Drive C:
![2019-03-07 23_34_11- c__users_john_appdata_roaming_code_user_settings json - clientapp - visual stu](https://user-images.githubusercontent.com/3343496/54007787-9a555f80-4131-11e9-9fd4-a88b487485d7.png)

**Comment by JimiC** [comment]
The `customIconFolderPath` was originally designed to give the user the ability to point the extension to where the custom icons are, considering that the user is distributing those icons along with the project, So basically, the `customIconFolderPath` should be somewhere near the projects' source code, preferable somewhere under the root folder of the project. And to be complete we implemented the use of "absolute" and "relative" paths.
In the case of a `*nix` OS this works regardless of where the custom icons folder lies as those OS don't have the concept of disk drives. On `Windows` it's a totally different thing. Yes. `customIconFolderPath` works if the custom icons folder is in the same drive as the project because the extension can figure out the relative path. But with different drives, this is not working.

Never the less, for completeness sakes, I'll try to figure out a way to accomplish that.

**Comment by JimiC** [comment]
I hade to refresh my knowledge on how `vscode` assigns the icon path. Turns out that icons path in the manifest has to be strictly relative paths to the extensions entry point folder (by the time of this writing it's `..../extensions/vscode-icons-team.vscode-icons-8.3.0/`). So unless you are on a `*nix` OS, the only way to make this work is to have the custom icons folder at the same disk drive as the extension or projection, or as mentioned in the wiki on a mapped network drive.
