### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by BaluErtl** [vscode-icons/vscode-icons#2024]
- Issue Type: `Performance`
- Extension Name: `vscode-icons`
- Extension Version: `8.6.0`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.33.1`

[vscode-icons-team.vscode-icons-unresponsive.cpuprofile.txt](https://github.com/vscode-icons/vscode-icons/files/3109656/vscode-icons-team.vscode-icons-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by JimiC** [comment]
Thank you for attaching the profile file. We'll investigate.

**Comment by JimiC** [comment]
I couldn't find anything helpful to point me to the cause. I suspect that the high CPU load is due to the synchronous way we execute our code. In `v9` we have switched to asynchronous code and we also bundle the code to make it load faster. I believe that these changes will have a positive impact on the issue.

We will keep the issue open for a little while longer and will monitor the new code behavior.

**Comment by BaluErtl** [comment]
@JimiC anyway, thanks for your precious time spent on thinking about the possible causes.
