### ISSUE TITLE
Contribution descriptions are set to config object's keys

### ISSUE THREAD

**Issue by smith-neil** [vscode-icons/vscode-icons#2072]
- [x] I'm sure this issue is not a _duplicate_.
- More info: Contribution descriptions are pulling and rendering the config object's keys instead of values. I'm seeing the same issue with English and German. I'm on Mac OS 10.14.5, vscode 1.34.0, vscode-icons 8.7.0.

<img width="1129" alt="Screen Shot 2019-06-04 at 3 43 33 PM" src="https://user-images.githubusercontent.com/1562853/58912400-8b099200-86df-11e9-917d-1bb4679f6318.png">
<img width="1124" alt="Screen Shot 2019-06-04 at 3 50 26 PM" src="https://user-images.githubusercontent.com/1562853/58913006-f1db7b00-86e0-11e9-81f7-8b2ca1f6ce20.png">

**Comment by JimiC** [comment]
Turns out this is a `vscode` visual bug. Investigating it, I searched for another extension that uses `nls` for translation support and found [yzhang-gh/vscode-markdown](https://github.com/yzhang-gh/vscode-markdown). If you search in `vscode` extensions sidebar for `markdown` and view the `Contributions` section for that extension, you will see the same visual bug.

Better report this to the `vscode` issues.

**Comment by JimiC** [comment]
Related https://github.com/microsoft/vscode/issues/54111

**Comment by vorfol** [comment]
If you disable ethernet connection and reload VS Code you will see correct labels.

**Comment by Omcsesz** [comment]
It is solved by now:

![image](https://user-images.githubusercontent.com/1839739/207160601-c5f47682-a641-45f4-87c3-2719a5af3a21.png)
