### ISSUE TITLE
[Icon Change] Clojurescript icon

### ISSUE THREAD

**Issue by KingDarBoja** [vscode-icons/vscode-icons#2083]
- [x] I'm sure this issue is not a _duplicate_.

The current Clojurescript icon (hence its file extension) is currently using the same icon as the Clojure language. There is a [Clojurescript Official Icon Repo](https://github.com/cljs/logo) with the proper svg and png files to replace it.

Of course, I can do such PR if the `vscode-icons` team is okay with that.

Cheers!

**Comment by jens1o** [comment]
> Of course, I can do such PR if the vscode-icons team is okay with that.

I'd be fine with that.

**Comment by JimiC** [comment]
This is tricky. Looking at the various `Clojure` related `vscode` extensions, most use `clojure` as a `language id`. From what I gathered so far the file extensions that need to be supported are: `clj`, `cljc`,  `cjm` and the proposed `cljs`. `Clojure` and `ClojureScript` need to be different associations but still need to be able to work together.

So, what we can do in order to support them correctly is:
- Add a new declaration in `SupportedExtension` for `clojurescript` with the proper icon
- Add `cljs` entry in the `extensions` attribute
- Add `clojurescript` as a potential `language id` and inform the various authors about it
