### ISSUE TITLE
Reconsider triggering search

### ISSUE THREAD

**Issue by roblourens** [vscode-icons/vscode-icons#2264]
I see that you use the findFiles API to detect the type of project: https://github.com/vscode-icons/vscode-icons/blob/5672568ef05b0d38798c3636f0c6551eb6c2a79f/src/pad/projectAutoDetectionManager.ts#L33

Please consider whether this is really necessary - searches can be very expensive, and then people file issues like this https://github.com/microsoft/vscode/issues/82136

You can search for package.json on the root without triggering an actual search, and it seems like that's what you really want. Just use `package.json` instead of `**/package.json`

**Comment by JimiC** [comment]
Our intention is not to search only on root but in every depth of a project structure to find a `package.json` file. There are projects that are not pure js but use js for the front-end part. We are aware that this search is expensive and that's why we offer the ability to disable the project auto detection feature.

**Comment by xgdgsc** [comment]
Thanks for the tip. It works. Might be better to disable by default.

**Comment by JimiC** [comment]
We have added a notice on the related [wiki page](https://github.com/vscode-icons/vscode-icons/wiki/Pad) recommending to disable `PAD` for large projects.
