### ISSUE TITLE
monorepo: vscode-icons has detected conflicting project icons

### ISSUE THREAD

**Issue by andreialecu** [vscode-icons/vscode-icons#2325]
I'm using [yarn workspaces](https://yarnpkg.com/lang/en/docs/workspaces/) to work with a monorepo in which I have both a NestJS and an Angular project.

I've been getting this popup:

![image](https://user-images.githubusercontent.com/697707/71590847-ad0eaa00-2b32-11ea-9516-a9a9dc6aa4b0.png)

As an example, `packages/angular-stuff` might be Angular while `packages/nest-stuff` would be NestJs, but they're both part of a main root workspace.

Is there a way to configure the extension to understand my setup?

**Comment by JimiC** [comment]
No. You can have one or the other, not both, hence the message.

**Comment by andreialecu** [comment]
Look into https://github.com/nrwl/nx which has almost 3K stars on github. It's a new dev paradigm for monorepos and one of the main directions it recommends is having an angular and nestjs project under the same root.

Hence this should be a pretty common request going forward.

**Comment by JimiC** [comment]
It's technically impossible what else can I tell you.

**Comment by robertohuertasm** [comment]
@andreialecu the problem here is that file icons can only been associated once. So, to make this clear to anyone wondering why this is not possible to overcome I'll put an example: both `Angular` and `NestJs` use files named as `controller, guard, module, pile and service`. As we cannot technically change the icon associated to these names depending on the location of the file, you have to decide which icon to show whenever you find these file names.

So, by using our [Fine Tuning](https://github.com/vscode-icons/vscode-icons/wiki/FineTuning) feature you could change the conflicting icons to a more neutral ones, but that's all that we can offer for the moment. 

Note that this is because a limitation on the current VSCode API, not in our extension functionality. Hope this helps to illustrate the question. 😀

**Comment by andreialecu** [comment]
I see. I didn't mean to sound pushy or anything, it's a minor issue. However, since monorepos and nx are gaining traction, this should be kept on some sort of roadmap for the future.

Looks like an issue should be opened in the VS Code repo to enable extensions to override icons on a per directory/per file basis.

**Comment by KingDarBoja** [comment]
I knew this was related to `nrwl/nx` as I thought about the possible conflicts that PAD system could generate for monorepos.

As @robertohuertasm said, it is not possible due to VSCode API but would be great if someone open a new ticket for that (if not already existing).

**Comment by JimiC** [comment]
@andreialecu Issue already exists on `vscode` repo. Team has stated that this is of no priority for them.

**Comment by JimiC** [comment]
I'm closing the issue as answered,
