### ISSUE TITLE
add support for mc files

### ISSUE THREAD

**Issue by TIBTHINK** [vscode-icons/vscode-icons#2479]
- [ ] I'm submitting an icon request:
  - Type: `minecraft`
  - Icon Name: `mcfile `
  - Sample original Icon:  there is none but im more than happy to make one
  - Extensions: `.mcmeta, .mcfunction,`
  - Filenames: ``
  - Language ids: ``

- Language Extensions:
- More info:

**Comment by KingDarBoja** [comment]
Hi @TIBTHINK 

Can you provide more info regarding this icon? where it comes from? Is there any vscode extension?

**Comment by JimiC** [comment]
Once again we had to do the searching.
`mcmeta`: https://minecraft.gamepedia.com/Tutorials/Creating_a_resource_pack#Creating_an_MCMETA_file
`mcfunction`: https://marketplace.visualstudio.com/items?itemName=arcensoth.language-mcfunction

**Comment by KingDarBoja** [comment]
Last time I had to deal with minecraft icons, suggested a box but was too big. This time, I searched the minecraft logo and keep only the "M" character.

![minecraft](https://user-images.githubusercontent.com/30560560/86502190-05369b00-bd66-11ea-9bce-cb5edf05d654.png)

Size: 1KB (4KB on disk).

**Comment by AdamRaichu** [comment]
Perhaps instead a creeper face. It's a bit more distinctive.

**Comment by cootshk** [comment]
`.mcmeta` is a format for describing animations (with json)
`.mcfunction` is a function to be run in game

**Comment by remcohaszing** [comment]
I’m a casual Minecraft (Java edition) player myself, and although I don’t do any modding or whatever, it would be cool to support Minecraft in vscode-icons. There are 2 Minecraft versions: Minecraft Java edition and Minecraft Bedrock edition.

To me, by far the most iconic Minecraft logo is the dirt block. This has been Minecraft logo for over a decade and it was the official SVG logo of the Minecraft launcher installed on my machine:

![A Minecraft dirt block](https://github.com/user-attachments/assets/37b56bd7-d82b-49c5-bcf5-e547a820df31)

This logo is pretty simple, but the pixelated pattern is very hard to optimize for SVG. Here’s an optimized version (26.7KB)

![A Minecraft dirt block](https://github.com/user-attachments/assets/7d7f1a4f-2770-4b61-9158-2d93271862df)

I came across [this blog post](https://www.minecraft.net/en-us/article/our-icons-are-changing), apparently they did some rebranding in 2023. The launcher as well as their [website](https://www.minecraft.net) and [Twitter](https://twitter.com/Minecraft) account now use the creeper face. I just updated the launcher and indeed, got the new logo:

![Minecraft creeper face](https://github.com/user-attachments/assets/8e7045d0-8183-4f80-b458-dc37085538f1)

Here’s an optimized version (554 bytes):

![Minecraft creeper face](https://github.com/user-attachments/assets/bd1ee674-a686-4179-bca0-49aa4df275bc)

The Java edition now uses a less detailed dirt block. The Bedrock edition now uses a less detailed version of one face of a dirt block.

The M logo @KingDarBoja proposed is instantly recognizable as part of Minecraft branding for the full logo, though it looks pretty old.

Searching for “Minecraft” in the Extensions Marketplace, I found the following Minecraft related extensions in the VSCode Marketplace:
- [Minecraft Bedrock Edition Debugger](https://marketplace.visualstudio.com/items?itemName=mojang-studios.minecraft-debugger) (Official)
  - Does not register anything file related
- [Minecraft Script](https://marketplace.visualstudio.com/items?itemName=Stevertus.mcscript)
  - Language IDs: `mcscript` (`.mcscript`)
- [Blockception's Minecraft Bedrock Development](https://marketplace.visualstudio.com/items?itemName=BlockceptionLtd.blockceptionvscodeminecraftbedrockdevelopmentextension)
  - Language IDs: `bc-mcfunction` (`.mcfunction`)
  - Language IDs: `bc-minecraft-language` (`.lang`)
  - Language IDs: `bc-minecraft-molang` (`.molang`)
  - Language IDs: `bc-minecraft-project` (`.mcdefinitions`, `.mcattributes`, `.mcignore`)
- [Minecraft Lang Colorizer](https://marketplace.visualstudio.com/items?itemName=zz5840.minecraft-lang-colorizer)
  - Language IDs: `minecraft-lang` (`.lang`)
- [Minecraft options.txt](https://marketplace.visualstudio.com/items?itemName=AdamRaichu.mc-options-txt)
  - Language IDs: `options-txt` (`.txt`)
- [Datapack Helper Plus by Spyglass](https://marketplace.visualstudio.com/items?itemName=SPGoding.datapack-language-server)
  - Language IDs: `mcdoc` (`.mcdoc`)
  - Language IDs: `mcfunction` (`.mcfunction`)
  - Language IDs: `mcmeta` (`.mcmeta`)
  - Language IDs: `snbt` (`.snbt`)
- [mcfunction](https://marketplace.visualstudio.com/items?itemName=Levertion.mcfunction)
  - Language IDs: `mcfunction` (`.mcfunction`)

There are more, but at some point I just stopped. As far as I understand, all of the above are related to Minecraft Bedrock edition.

Also several extensions register JSON schemas. Many of these can also be found in the [JSON Schema Store](https://www.schemastore.org/json/). Unfortunately most of these use globs, so we can’t assign icons to them. One exception though is that some JSON files use the `.mcmeta` file extension. We can assign an icon for those.

There’s also [Bukkit](https://dev.bukkit.org/), which is a popular framework to author and manage Minecraft Java edition plugins. I don’t know what files it uses exactly, but one is `bukkit.yml`

Minecraft stores its data in the `~/.minecraft` folder. This folder contains a bunch of files. Most of these files aren’t suitable for icons, but the `.minecraft` folder would be. Also `.mca` files, which are binary files containing Minecraft world data.

I think it would be cool to distinguish a bit more, but I suggest we use the creeper face logo for the following language IDs:
- `bc-mcfunction`
- `bc-minecraft-language`
- `bc-minecraft-molang`
- `bc-minecraft-project`
- `mcdoc`
- `mcfunction`
- `mcmeta`
- `mcscript`
- `minecraft-lang`
- `options-txt`
- `snbt`

And the following file extensions:
- `.mca`
- `.mcmeta` (Because these should really use the `json` language ID to get JSON schema support)

Additionally we can add a folder icon for the `.minecraft` folder.

An icon for `bukkit.yml` would be cool too, but it’s out of scope, and the Bukkit logo is also a pixelated icon hard to optimize for SVG.
