### ISSUE TITLE
[Icon Request] Add  Microsoft sql server logo

### ISSUE THREAD

**Issue by GNSubrahmanyam** [vscode-icons/vscode-icons#2485]
![image](https://user-images.githubusercontent.com/18217008/81495077-40b76a80-92cb-11ea-9c98-f829e1737344.png)

- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: ``
  - Icon Name: ``
  - Sample original Icon: ![logo]()
  - Extensions: ``
  - Filenames: ``
  - Language ids: ``

- Language Extensions:
- More info:

**Comment by KingDarBoja** [comment]
Hi @GNSubrahmanyam 

This is already supported on our file icon list. You need to install a vscode extension like [mssql](https://marketplace.visualstudio.com/items?itemName=ms-mssql.mssql) to make it work.

The default `.sql` icon is not the same as the Microsoft sql server one as this is a wide used extension for other sql servers. In that case, please take a look at [custom](https://github.com/vscode-icons/vscode-icons/wiki/Custom) doc section in order to replace it with your own icon.

Cheers!
