### ISSUE TITLE
Roughly half the icons are not loading

### ISSUE THREAD

**Issue by pcsagan** [vscode-icons/vscode-icons#2673]
This addon doesn't seem to be loading icons for a random half of the supported file types. I don't know what I can do to figure out what's wrong, but I did confirm that jinja, cfm, and gulp should be supported by this extension.
![icons_not_working](https://user-images.githubusercontent.com/36746349/103421033-a6b17480-4b70-11eb-9bcd-e072d3800a63.png)

**Comment by robertohuertasm** [comment]
Some of the icons are just enabled when a extension is installed that supports a specific language ID. Try installing a jinja extension.

**Comment by pcsagan** [comment]
I have "Better Jinja" installed which correctly formats my jinja files with .jinja extensions, but has no effect on the icon.

**Comment by robertohuertasm** [comment]
I see... `Better Jinja` uses lots of different language ids. For the moment we only support `jinja` language id. The quick fix is just to set a file association in your vscode settings:
```json
 "files.associations": {
    "*.jinja": "jinja"
  }
```

I'll provide a fix for this.

**Comment by robertohuertasm** [comment]
@pcsagan for the rest of files, you need a extension declaring a `language id` for them to be enabled. The way `vscode` sets the icon is `file name` > `file extension` > `language id`. This means that if we declared file extensions authors creating language extensions wouldn't be able to define which extensions are the right ones. Or better put, they wouldn't be able to overwrite our defaults. That's why we decided to completely rely in language extensions.

In the end, someone working with some specific files will install a language extension and in the case he won't, the user can always configure file-icon associations.

Btw, there's a new PR adding more language ids for jinja.

**Comment by robertohuertasm** [comment]
For `cml` it seems that they decided to change again the `language id` (see #1079). I'll provide another PR.

**Comment by robertohuertasm** [comment]
Forgot to mention that the `.gulp` extension is not supported. See [what we're currently supporting for Gulp](https://github.com/vscode-icons/vscode-icons/wiki/ListOfFiles#gulp).
