### ISSUE TITLE
File icons do not change based on the current theme type (light or dark)

### ISSUE THREAD

**Issue by Gliptal** [vscode-icons/vscode-icons#2765]
- [x] I'm sure this issue is not a _duplicate_.

Here's an example, with the [Crystal](https://github.com/vscode-icons/vscode-icons/wiki/ListOfFiles#crystal) icon:

- Light (Visual Studio) theme:
![Code_ZmCcb32Ggy](https://user-images.githubusercontent.com/3907646/117149353-6fb9cc80-adb7-11eb-80b0-5528da74ddb9.png)

- Dark (Visual Studio) theme:
![Code_ekPL4jSfNL](https://user-images.githubusercontent.com/3907646/117149503-91b34f00-adb7-11eb-824c-feb5c3addfa9.png)

Is there something I'm missing in configurating vscode-icons?

> Version: 1.56.0 (system setup)
> Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
> Date: 2021-05-04T22:09:06.405Z
> Electron: 12.0.4
> Chrome: 89.0.4389.114
> Node.js: 14.16.0
> V8: 8.9.255.24-electron.0
> OS: Windows_NT x64 10.0.19042
>
> vscode-icons 11.4.0

**Comment by KingDarBoja** [comment]
Which version of vscode-icons are you using?

**Comment by Gliptal** [comment]
Apologies, I completely skipped the version information. OP updated.

**Comment by robertohuertasm** [comment]
@Gliptal is this still ongoing?

**Comment by Singond** [comment]
I have just tried with `v11.12.0` but could not reproduce the issue. The Crystal icon rendered dark in the default light theme.

![image](https://user-images.githubusercontent.com/23259915/176781492-735dbeb3-4a7e-48be-a79d-c88cd5b2c5c7.png)

FWIW, the built-in Seti icon theme seems to suffer a similar issue, because it only contains a light grey version of Crystal icon.
Vscode-icons seems to be fixed though.

> Version: 1.67.2
> Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
> Date: 2022-05-19T00:31:55.273Z
> Electron: 17.4.1
> Chromium: 98.0.4758.141
> Node.js: 16.13.0
> V8: 9.8.177.13-electron.0
> OS: Linux x64 5.15.48-1-MANJARO

**Comment by robertohuertasm** [comment]
Thanks @Singond for confirming this!
