### ISSUE TITLE
vscode-icons super slow on startup!

### ISSUE THREAD

**Issue by DillPickle80** [vscode-icons/vscode-icons#2959]
- [x] I'm sure this issue is not a _duplicate_.
- [ ] I'm submitting an icon request:
  - Type: ``
  - Icon Name: ``
  - Sample original Icon: ![logo]()
  - Extensions: ``
  - Filenames: ``
  - Language ids: ``

- Language Extensions:
- More info:
The extension in itself is great, but it's activation time is sooooooooo looooooooooooong!
Opening the "Developer: Startup Performance" log, it's "Finish Activate" time is almost 30 seconds, 29851 ms to be more precise! It's Activation Event is set at (*), which is normally bad for performance, couldn't it be activated otherwise, like "onStartupFinished", or even better only when opening the Project Explorer pannel if it's even possible?

I love this extension but i had to uninstall it because of this.

**Comment by robertohuertasm** [comment]
Hi @DillPickle80, thank you for submitting this. I'm wondering if the fact that the extension is taking so long is because some particularity of your environment.

I'm not getting those numbers at all: 

<img width="692" alt="image" src="https://user-images.githubusercontent.com/696981/163828513-74ebb140-f7fb-4cae-986d-c80e626c137f.png">

**Comment by DillPickle80** [comment]
Yes in fact it is. For some reason which i'm having a hard time figuring out my remote-ssh vscode setup is perfectly fast on my home network as well as my mobile network, but not on my job network. We tried tweaking firewall settings for my remote machine but nothing has solved the problem so far. After investigation i found that while most extensions runs perfectly smooth, a handful of them are seriously impacted including vscode-icons. I also noticed that some of them seems ok in isolation but starts slowing vscode significantly when combined with other extensions, notably Python.

Sorry i forgot to specify this, it clearly is very important information. I will edit the review i left on the Extension Marketplace.

**Comment by robertohuertasm** [comment]
@DillPickle80 thanks for your answer. I'm going to close this unless you feel that we should keep this open.

**Comment by JimiC** [comment]
@DillPickle80 Since I'm working with `Python` too on `VSCode`, I have noticed that the linting service for `Python` (I'm using `py-lint`) is slowing my `VSCode` to the point where even typing is halted.

Try disabling linting.
![image](https://user-images.githubusercontent.com/1716442/166140439-d14a9c3c-bd9c-4714-ac03-473406db3871.png)
