### ISSUE TITLE
Assembly icon is not visible but another icon is working fine

### ISSUE THREAD

**Issue by wawan-ikhwan** [vscode-icons/vscode-icons#3079]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Information:

I know it looks duplicate but the old issue didn't give me solution, I have tried to custom icon for assembly through this documentation but it seems failed. I reinstall extension but still same.

It said assembly icon is supported with id ```.asm```, but why it's not appear in my side?
![image](https://user-images.githubusercontent.com/72451078/178134037-53093c35-8319-4c7c-baef-71256aeb04f5.png)

**Comment by robertohuertasm** [comment]
What have you done exactly to make this work?

**Comment by mirao** [comment]
I have the same issue. A generic icon (instead of specific one) is shown for the `asm` or `s` files in Explorer and Source Control view:

![image](https://user-images.githubusercontent.com/12584138/204127938-dd368083-5729-48f3-8925-2b85b4f7e24c.png)

If I change icon theme to Seti, some specific icons are shown:

![image](https://user-images.githubusercontent.com/12584138/204127970-8b1269e3-22e3-4941-b1d6-53d3ed5246bf.png)

**Used SW:**

- VSCode 1.73.1
- vscode-icons-team.vscode-icons 12.0.1

**Comment by robertohuertasm** [comment]
Ok, it seems we have an issue. The extension was relying on [this other extension](https://marketplace.visualstudio.com/items?itemName=13xforever.language-x86-64-assembly) but they have changed the language id. I'll create a PR for this.

**Comment by mirao** [comment]
The icon is present now (v12.3.0), but it doesn't look well in default color theme Dark+. It's hard to recognize the icon on black background.

![image](https://user-images.githubusercontent.com/12584138/232213075-528c0716-564d-4760-b329-cfcbe072a2e6.png)

Is it a VSCode behavior how an icon looks in specific color theme or is it needed to have different icons for light/dark themes? Or maybe if the icon was lighter it would look better.

**Comment by mirao** [comment]
I must to zoom it in in order to see that there is the "ASM" text.

![image](https://user-images.githubusercontent.com/12584138/232215044-ea54cf39-2497-47ff-9d4d-c085fd899cd9.png)
