### ISSUE TITLE
script folder icon override to default folder icon does not work

### ISSUE THREAD

**Issue by JanCervak** [vscode-icons/vscode-icons#3233]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Information:

Folder named "script" or "scripts" defaults to a specific icon ([ListOfFolders](https://github.com/vscode-icons/vscode-icons/wiki/ListOfFolders)).

When trying to override to default folder icon in a workspace settings:
```
"vsicons.associations.folders": [
	{ "icon": "folder", "extensions": ["scripts"] }
]
```
the scripts folder icon completely disappears: 
![image](https://user-images.githubusercontent.com/10254860/219319125-59fcd8d8-90b2-45ab-8279-2c4d1b4174ab.png)

When overriding with for example "audio" icon:
```
"vsicons.associations.folders": [
	{ "icon": "audio", "extensions": ["scripts"] }
]
```
it works as expected and the audio folder icon is displayed for the scripts folder:
![image](https://user-images.githubusercontent.com/10254860/219319485-1b1c8587-53f7-4151-9eff-4fb40863e168.png)

Versions:
vsicons v11.4.0
vs code 1.74.3

**Comment by JanCervak** [comment]
No solution planned? A year later, issue still the same (vsicons 12.7.0, vs code 1.86.2)

**Comment by JimiC** [comment]
Nothing to be fixed, Pls read again https://github.com/vscode-icons/vscode-icons/wiki/Custom
Hint: You are trying to customize `scripts` by altering the default folder icon.

**Comment by JanCervak** [comment]
@JimiC, the provided link describes how to add a _user_ icon to be used by vscode-icons. I want just to "revert back" to ordinary folder icon for a folder named _scripts_. In my sandpit workspace it has no special meaning, so the distinction is just annoying. For it is possible to change to other icon from the standard set [ListOfFolders](https://github.com/vscode-icons/vscode-icons/wiki/ListOfFolders), this seems to be a bug.

**Comment by JimiC** [comment]
Let me get this clear. You want the default folder icon to be shown for a folder named `scripts`, right?

**Comment by JimiC** [comment]
What you are trying to do is to *customize* your `scripts` folder, thus you fall into the [`customization`](https://github.com/vscode-icons/vscode-icons/wiki/Custom) feature.
The way you are trying to use the feature is not the way it's designed to work.

Let me explain. `VSCode` has 3 types of folder icons that we can declare.
1. Default folder icon (declared as `default_folder_{state}`)
2. Root folder icon (declared as `default_root_folder_{state}`)
3. Any other folder icon (declared as `folder_type_{name}_{state}`

Your case is case 3, thus you need to follow the `customization` instructions.
The only upside in your case is that we already provide the icon you want to use, so you don't have to create any.

What you can do is to copy the 2 `default_folder_{state}` icons and name them ``folder_type_folder_{state}`, since you use `"icon":"folder"` in your declaration and place them in a `vsicons-custom-icons` folder as instructed.

This ain't easy you say? It is what it is, unfortunately.

**Comment by JanCervak** [comment]
@JimiC, absolutely, I want to _customize_ the visual appearance, unfortunately you are not suggesting [Customization](https://github.com/vscode-icons/vscode-icons/wiki/Customization), but [Custom Icons](https://github.com/vscode-icons/vscode-icons/wiki/Custom) wiki page. Anyway, your described solution might be a working workaround.

Fortunately, the 'Custom Icons' section was helpful, for there is stated the icon naming pattern. Together with the content of the extension-bundled icons folder it is clear, that the default file & folder icons are something special - these do not follow the pattern. 

For my intent, I've probably started with examples [Fine Tuning](https://github.com/vscode-icons/vscode-icons/wiki/FineTuning) together with [ListOfFolders](https://github.com/vscode-icons/vscode-icons/wiki/ListOfFolders). As suggested in the issue description, icon names in the list work fine except for the _special_ 'folder' and 'root_folder'.

Finally, by a guess I've found out simple working solution - omitting the icon name:
```
"vsicons.associations.folders": [
	{ "icon": "", "extensions": ["scripts"] }
]
```
![image](https://github.com/vscode-icons/vscode-icons/assets/10254860/1c1e425e-65e0-4d5c-a347-0b6e02a2e9e7)

PS: I hope this won't be subject to any future change:)

**Comment by JimiC** [comment]
1. `Custom Icons` is a sub subject of `Fine tuning` which is a sub subject of `Customization`. `Customization` page doesn't provide much info, does it? I was merely pointing you to a direction which in the end helped you, right?
2. The way you solved it, is simply because `vscode` defaults to the default folder icon when an icon file is not specified via `icon` definition. You should thank `vscode` devs for that, not us.

Anyways, glad you figured it out.
