### ISSUE TITLE
[Icon Request] OpenCL kernels

### ISSUE THREAD

**Issue by Se6** [vscode-icons/vscode-icons#621]
- I want to create an icon request:
      - Type: extension
      - Icon Name: OpenCL
      - Sample original Icon : [https://upload.wikimedia.org/wikipedia/en/1/1c/OpenCL_Logo.svg]
      - Extensions: .cl, .opencl
Thanks!

**Comment by JimiC** [comment]
I'm afraid we can't do this (https://developer.apple.com/softwarelicensing/agreements/opencl.php)

**Comment by Se6** [comment]
Indeed. Thanks for looking into it, sorry for the waste of time.

**Comment by JimiC** [comment]
If you can propose another icon that is not trademarked, we are all in into that.

**Comment by JimiC** [comment]
I found this, which resembles but it's not the same.

![opencl_protocol_open_pgp_3d](https://cloud.githubusercontent.com/assets/1716442/21849825/78029420-d810-11e6-99b9-4f9c4425b116.png)

If we only could find it in SVG.

**Comment by Se6** [comment]
Ah yes, pretty close. Otherwise, there are the different, but could do: https://openclipart.org/detail/81913/speedometer

**Comment by Se6** [comment]
Or: https://openclipart.org/detail/237767/evaluation-score

**Comment by JimiC** [comment]
In order to bypass the licensing issue, I made this icon in `SVG`.

1x ![file_type_opencl](https://cloud.githubusercontent.com/assets/1716442/22152350/1ff51754-df2b-11e6-8d70-74ae84b27b05.png)
4x ![file_type_opencl 4x](https://cloud.githubusercontent.com/assets/1716442/22152358/37209e4e-df2b-11e6-9de1-6cf44f64d644.png)

**Comment by Se6** [comment]
Very nice indeed!! Thanks a lot.
