### ISSUE TITLE
vba icons

### ISSUE THREAD

**Issue by spences10** [vscode-icons/vscode-icons#646]
**Checklist:**

- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request:

Can the vba icon set be included in this repo?
[vscode-vba-icons](https://github.com/spences10/vscode-vba-icons)

Here's the excerpt from the `package.json` file, there's no SVG for them I'd be happy to make some [because there's none out there] fork and make a PR if they will be included? 

Thanks :+1: 

        "languages": [
            {
                "id": "vba",
                "extensions": [
                    ".bas",
                    ".cls",
                    ".frm",
                    ".sht",
                    ".wbk"
                ],
                "aliases": [
                    "vba",
                    "VBA"
                ]
            }
        ]

**Comment by JimiC** [comment]
Looks like a special case to me as it also can be associated with `languageId`.
@spences10 Give me some time to see how this can work.

**Comment by spences10** [comment]
@JimiC that's how I understood it worked, no? To have the icons associated with the language?? Or are the icons associated by extension type?

It was just an exploratory comment really as I have no SVG icons for vba right now.

And of course vba is a special case :smile_cat: why do you think I used crayon for the extension image :smile: 
![image](https://cloud.githubusercontent.com/assets/234708/22027903/44b56bc6-dccd-11e6-95c1-705c90c9d27b.png)

https://github.com/spences10/vscode-vba/blob/master/images/logo.png?raw=true

**Comment by JimiC** [comment]
The way we use `language id` association is that every file extension supported by the `id` gets associated with a single icon. You have icons for different file extensions. This has to be investigated how it works.

**Comment by JimiC** [comment]
As I suspected there are several issues implementing this.

1. `.bas` is already covered via the `vb` `language id` (https://github.com/Microsoft/vscode/blob/master/extensions/vb/package.json#L9)
2. `language id` association allows only one icon to be associated with several file extensions.

In order to support the `.cls` and `.frm` file extensions with their own icons, we will have to avoid using the `language id`, meaning that those extensions will be covered outside the `language id` and their icons will be shown regardless whether the user has the `VBA` extension installed or not.

So either we will go with the `language id` association and all `vba` extensions (expect `.bas`) will have a `vba` icon
or
we go with individual icons for each `vba` file extension without using the `language id`.

**Comment by spences10** [comment]
Go with `language id` 👍

**Comment by spences10** [comment]
Can this be closed now?

**Comment by robertohuertasm** [comment]
If I'm not wrong now it's showing the same icon for all the `vb` extensions which is not what you wanted, is it? If that's the case then this should not be closed.

**Comment by JimiC** [comment]
Only `.bas` is covert by the internal `VB` extension. We haven't found an icon for your extension yet. So until be do let's keep this open.

**Comment by JimiC** [comment]
@spences10 I wouldn't close the issue. The fact that we haven't done anything for it, is simply because we haven't found any suitable icon.
I leave it up to you to reopen it if you like.

**Comment by spences10** [comment]
Feel free to open your own issue to resolve it, I'm no longer interested in it being resolved

Thanks

**Comment by jens1o** [comment]
well, I think we can stick to the same issue.

**Comment by spences10** [comment]
Hi, I'm not interested in the outcome of this or if it ever get resolved, as a result I don't want to see this in my open issues.

Please, can you respect my wishes and leave it closed.

Many thanks.
