### ISSUE TITLE
Gadget and uslx icons

### ISSUE THREAD

**Issue by xiaofengqinyu** [vscode-icons/vscode-icons#658]
- I'm sure this issue is not a *duplicate*.
- I want to create an icon request(if not, remove these lines below):
      - Type: [extension]
      - Icon Name: [gadget][uslx]
      - Sample original Icon (32x32/svg/transparent whenever possible): [url]
      - Extensions: .gadget,.uslx

**Comment by JimiC** [comment]
We highly appreciate if you can give us more info on the related software.

**Comment by xiaofengqinyu** [comment]
The uslx file is piece of html code,the gadget file is a collection of html,js,css to organize a function.

**Comment by tracker1** [comment]
is `.uslx` a specific file extension for a particular program/application or set of programs?  Google isn't coming up with anything.  Or is it `.gadget`[1]

If it's .gadget, it's a zip file container... is it the output of a process?  it seems like it wouldn't be something you'd manipulate in vscode directly (can it be a directory suffix?)

I'm asking because I had to do a little searching, and I'm still not sure if I'm familiar with what you are wanting/expecting?

[1] https://fileinfo.com/extension/gadget

**Comment by JimiC** [comment]
Expanding @tracker1 question, providing links that explain the software using those extensions would be more informative.
