### ISSUE TITLE
Autodetection enhancement

### ISSUE THREAD

**Issue by robertohuertasm** [vscode-icons/vscode-icons#673]
I have this case where I open a project which is not angular. The autodetection tool tells me that and let's me decide what to do. I don't mind disabling the icon and I choose 'close'. Then the settings.json gets modified with a `vsicons.presets.angular: true` and provided that I'm using Git I get a change alert.

It would be nice if we could detect such scenario: closing the popup while having a true default.

**Comment by JimiC** [comment]
This is the side effect of not having the ability to change the state of the setting on the fly.
The problem lies with `vscode` itself not persisting the change before it executes the `reload` command.
To workaround this we are forced to change the setting beforehand of showing the message and revert it if the user chooses to `close`.
Another workaround would be to introduce a delay ourselves but on machines with slow `io` this is not guaranteed to work.

I have raised an [issue](https://github.com/Microsoft/vscode/issues/18660) @ `vscode` repo.

**Comment by JimiC** [comment]
I found a workaround on this but the avoidable side effect is that `vscode` modifies the `settings` file it doesn't respect the formatting. This also happens in the current implementation.

**Comment by JimiC** [comment]
And while we are at this how about we make the message shown auto-dismissable, like after 10 secs it self-invokes `Close`?

**Comment by robertohuertasm** [comment]
@JimiC you mean that the indentation of the json wouldn't be kept?

**Comment by JimiC** [comment]
@robertohuertasm Exactly but this is something that is happening also with the current implementation.

**Comment by robertohuertasm** [comment]
np for me. This is something totally out of our control as it's managed by the vscode api so... 👍

**Comment by JimiC** [comment]
I'll submit the PR tomorrow cause I forgot to push it and it sits on the work's machine.
