### ISSUE TITLE
Odd icon for Rakefiles

### ISSUE THREAD

**Issue by Alhadis** [vscode-icons/vscode-icons#698]
Redirected here from donovanhiland/atom-file-icons#1, so I'll just copy-and-paste what I wrote:

--------------

Hey there,

I'm wondering where the choice of icon for Rakefiles came from. Was it [sourced from this](http://www.rubyrake.org/about-us/)?

<img align="center" hspace="20" src="http://www.rubyrake.org/wp-content/uploads/2016/09/logo-ruby.png" alt="Ruby Rake logo" valign="middle" /> <img align="center" src="https://cloud.githubusercontent.com/assets/2346707/22421573/f36a8e58-e73b-11e6-8862-25cc498d41c2.png" width="128" alt="Rakefile icon" valign="middle" />

If so, that page's description would suggest it's not at all connected with Ruby:

> **Ruby Rake Software** is the creation of an experienced master of software industry Mr. Rake. The software guru holds a double Masters in Engineering and Computer Sciences with certified courses in software from top universities of the world…

The icon in particular even seems like a stock logo, going by a [reverse image search](https://www.google.com/searchbyimage?&image_url=https://cloud.githubusercontent.com/assets/2346707/22421573/f36a8e58-e73b-11e6-8862-25cc498d41c2.png).

To the best of my current knowledge, Rake doesn't have a logo.

**Comment by JimiC** [comment]
> To the best of my current knowledge, Rake doesn't have a logo.

Exactly and that's why we chose this icon to differentiate it from Ruby. It may be not related by we liked the icon.

Elaborating on your [comment](https://github.com/donovanhiland/atom-file-icons/issues/1#issuecomment-276174725) @ `atom-file-icons`, in the next version we are supporting `Chef`, which means that `'chefignore', 'Berksfile', 'Berksfile.lock', 'Policyfile'` will be associated to that.

**Comment by Alhadis** [comment]
Fair enough, then.
