### ISSUE TITLE
Only colour when changed?

### ISSUE THREAD

**Issue by cloudyan** [vscode-icons/vscode-icons#795]
Can you support 'Only colour when changed', like file-icons in atom

**Comment by JimiC** [comment]
Please elaborate. Not everyone used `atom`.

**Comment by JimiC** [comment]
@cloudyan Closing due to lack of response.

**Comment by robertohuertasm** [comment]
I think this was already requested long ago (see #83) but unfortunately this is not possible yet. 

I see that `atom's file-icons` have already created an [extension for vscode](https://github.com/file-icons/vscode) and certainly they will try to implement as much as they have in the atom version. 

As far as I know, this is not currently possible due to the current vscode theming api.

**Comment by JimiC** [comment]
@robertohuertasm I so mush suspected that was the case but you can never be sure. Thanks for the insight though.
