### ISSUE TITLE
Lose icons customization each time extension update

### ISSUE THREAD

**Issue by maroy1986** [vscode-icons/vscode-icons#857]
**Checklist:**

- [x] I'm sure this issue is not a *duplicate*?

Hi, I noticed that each time there's a new update available for vscode-icons, after installing it and reload Visual Studio Code, I loose all my icons customization I made into my settings.json. There still there but not applied. The only thing I need to get them back is to open the command palette and choose `Icons: Apply icon customization `. Then everything is back to normal.

This is becoming an hassle to do each time the extension is updated. Is there a reason why you need to reset those when you update the extension?

That would be great If it keeps the customization or reapply them automatically when the extension is updated and reloaded.

Thanks!

**Comment by jens1o** [comment]
I don't have this problem. I'd set a custom icon for php, and it still works when the extension got updated.

**Comment by maroy1986** [comment]
Forget to say, it's a customization for a folder icon. Here's how I defined my customization in my settings.json file :
`{
...
    "vsicons.projectDetection.autoReload": true,
    "vsicons.associations.folders": [
        { "icon": "test", "extensions": ["tests", "test", "_test", "__tests__", "__test__", "spec", "specs"], "format": "FileFormat.svg" }
    ],
...
}`
Every time the extension is updated, I loose it. Again this morning I had to reapply it.

**Comment by jens1o** [comment]
I'll take a look when we publish the next update. Stay tuned. Maybe the rest of the team has a idea...

**Comment by JimiC** [comment]
According to the code, the flow is as follows:

1. You are presented that a new version is available.
2. You are asked by `vscode` to reload in order for the new version to get activated.
3. Upon reloading after a few you are presented with the extensions "welcome" message if you haven't disabled it in a previous update,
4. A few secs later another message appears telling you to restart `vscode` in order to apply your customizations.

Now, to be honest, our test cases don't cover custom folders and this is on us. We apologize for that.
I'll make sure to investigate it further.

**Comment by JimiC** [comment]
@maroy1986 After testing the flow, with the settings you provided, I noticed the following:

- The flow works as expected (although it needs to correct some side effects, see below).
- You are presented with the message to 'Restart' in order for the customizations to be applied.
- Because you have `autoReload` set to `true` you probably don't get to see it because `vscode` restarts upon showing the message.
- The customization gets applied.
- Side effect: Although the customizations are applied, you get presented again with the message to `Restart`. This needs to be fixed.

**Comment by JimiC** [comment]
Additionally. In case you are on a non Angular project `vscode` will NOT auto restart and you will be presented with the message to 'Restart' in order for the customizations to be applied.

**Comment by JimiC** [comment]
Conclusion: With your settings, if you update and you are 

- on an Angular project, `vscode` will auto restart and customizations are applied.
- on a non-Angular project, you will be presented with a message to restart in order for the customizations to be applied.

**Comment by Bank5z0rSqt** [comment]
I like the addon, and i never usually post anything at github, but as a user i MUST SAY please calm the fk down with daily updates, why so damn often? Release larger set at once, it's really annoying to see that blue bubble on packages tab and every damn time its vscode-icons to update. Delete this message or do w/e you wanna do with it. Just wanted to point it out.

**Comment by JimiC** [comment]
@Bank5z0rSqt Thanks for your comment. We welcome any criticism as long as it's kept in a civilized manner.
Currently, the release schedule is one release per 2 weeks. When a bug is identified and fixed a 'patch' version is released out of the schedule. This ensures that the user experience of the extensions is the best possible. We are sorry that you feel this way, but the extensions quality is a priority for us.

**Comment by robertohuertasm** [comment]
I was about to write some comment about @Bank5z0rSqt but thought that @JimiC has put my ideas in a much nicer way.

**Comment by maroy1986** [comment]
@JimiC To clarify, i'm on a non-angular project. So basically, if I remove the auto-reload setting, set `vsicons.presets.angular` to false, then on the next update everything should be ok?

Just to remember, I'm still talking about **folder icon customization**, not file. Just to be sure you didn't forget it while into it :)

So here's what I have now based on what you said:
>   "vsicons.presets.angular": false,
>   "vsicons.associations.folders": [
>     { "icon": "test", "extensions": ["_test"], "format": "FileFormat.svg" }
>   ]

**Comment by JimiC** [comment]
@maroy1986 Yes, I referring to folder icon customization as I used your settings while testing. If you are on a non-Angular project while updating you will be presented with a message to restart in order for the customizations to be applied, regardless of what you set the `angular` preset. Notice that the `angular` preset is a `Workspace` level setting while `folder association` is a `User` level one.

**Comment by maroy1986** [comment]
@JimiC Interesting. Otherwise, is there any way to manually trigger the update workflow so I can see if it works after changing those things or I have to wait until your next update to see if it fix my folder icons customization getting lost again?

**Comment by JimiC** [comment]
Clone the repo and replace `settingsManager.isNewVersion()` with `true` @ https://github.com/vscode-icons/vscode-icons/blob/master/src/index.ts#L24

**Comment by coreyfarrell** [comment]
I've just reproduced this issue updating to 7.7.0, I lost custom icons for folders and files.

1. I installed updates for C/C++, ESLint and vscode-icons
2. Hit reload after installing all updates.
3. After reload my icons were lost (I expected this).
4. I was presented with another 'reload' button, I pressed it.
5. Still no custom icons.
6. I pressed F1, hit `Icons: Apply Icons Customization`, then hit Restart.
7. All is fine again.

I'm guessing the 'reload' button I was given in step 4 was not from vscode-icons since vscode-icons gives a "Restart" button after applying customizations.  Possibly the reload happened too quickly / before vscode-icons finished it's upgrade process?  Restarting VSCode is an annoyance so updating multiple extensions at the same time is pretty common for me.

**Comment by JimiC** [comment]
@coreyfarrell Can you remember 
1. When you updated the extension did you had opened an `Angular` or non-`Angular` project?
2. What is the value of `vsicons.projectDetection.autoReload` in your `settings.json` file?

**Comment by coreyfarrell** [comment]
@JimiC:
1. I do not work with any Angular projects, my primary project does contain an `html` folder with Polymer *.html files.
2. I do not have vsicons.projectDetection.autoReload set.  All of my "vsicons.*" settings are in the global settings.json as below:
``` json
{
    "vsicons.associations.files": [
        { "icon": "polymer", "extensions": ["html"], "overrides": "html", "format": "svg" },
        { "icon": "favicon", "extensions": ["index16.png", "index32.png", "index48.png", "index64.png", "index128.png", "index256.png"], "filename": true, "format": "svg" },
        { "icon": "rpm", "extensions": ["spec","spec.in"], "format": "svg" }
    ],
    "vsicons.associations.folders": [
        { "icon": "src", "extensions": ["html"], "format": "svg" },
        { "icon": "test", "extensions": ["t"], "format": "svg" }
    ]
}
```

**Comment by JimiC** [comment]
@coreyfarrell I'll try to reproduce using your settings.

**Comment by JimiC** [comment]
@coreyfarrell I found the bug.
For the devs reading this, we were updating the settings version before the check in the `autoApplyCustomization` function.

**Comment by maroy1986** [comment]
It works great now! Hasn't been easy to spot but happy you found it! Good job! Thanks!
