### ISSUE TITLE
[Icon Request] Support for .guard.ts in Angular 2+

### ISSUE THREAD

**Issue by juergenzimmermann** [vscode-icons/vscode-icons#872]
Angular 2+ provides CanActivate and CanDeactivate guards which are typically implemented in files with the extension .guard.ts. It would be nice if VSCode Icons would support these files.

**Comment by jens1o** [comment]
Do you have a suggestion for the look, or just the normal angular icon?

**Comment by JimiC** [comment]
Valid point.

**Comment by juergenzimmermann** [comment]
Maybe the normal angular icon with just yellow ("warning", "guard") instead of red.

**Comment by JimiC** [comment]
@juergenzimmermann We already use that color. We better leave the color choice to @robertohuertasm which is the lead artist here.

**Comment by robertohuertasm** [comment]
See #900 for color proposal. As yellow was already taken I'd suggest gold. 

Although it is crossing through my mind the idea of changing the colors association:

- Services would be green instead of blue.
- Directives would be blue instead of green.
- Routing would be gold instead of yellow.
- Guards would be yellow instead of gold.

So basically, it would be switching `services-directives` and `routing-guards`.

**Comment by jens1o** [comment]
hmm. I got used to it...

**Comment by JimiC** [comment]
No objection from me.

**Comment by robertohuertasm** [comment]
@jens1o, I've finally decided to just change `routing vs guards` and not to fool users to much with color combinations, so services and directives stay the same.

**Comment by jens1o** [comment]
Okay.
